/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as airdropSol from "./Airdrop.sol";
export type { airdropSol };
import type * as erc1155Sol from "./ERC1155.sol";
export type { erc1155Sol };
import type * as icoSol from "./ICO.sol";
export type { icoSol };
import type * as liquidityProviderSol from "./LiquidityProvider.sol";
export type { liquidityProviderSol };
export type { Lock } from "./Lock";
